{
 "title": "Capteurs ambiants et batterie",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \"temperature_ambiant\" AS \"Température\" \nFROM \"environnement\" \nWHERE $timeFilter \n"
    }
   ]
  },
  {
   "title": "Luminance",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \"luminance_ambiant\" AS \"Luminance\" \nFROM \"environnement\" \nWHERE $timeFilter "
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \"co2\" AS \"CO2\" \nFROM \"environnement\" \nWHERE $timeFilter \n"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \"batterie_pourcentage\" AS \"Batterie\" \nFROM \"environnement\" \nWHERE $timeFilter \n"
    }
   ]
  }
 ]
}