{
 "title": "Humidité",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Humidité Ambiante",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  \"humidite_ambiant\" AS \"Humidité Air\"\nFROM \"environnement\" \nWHERE $timeFilter \n"
    }
   ]
  },
  {
   "title": "Humidité Oyas",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  \"humidite_oya_1\" AS \"Horizontal Proche\",\n  \"humidite_oya_2\" AS \"Horizontal Loin\",\n  \"humidite_oya_3\" AS \"Profondeur Proche\",\n  \"humidite_oya_4\" AS \"Profondeur Loin\"\nFROM \"environnement\" \nWHERE $timeFilter \n"
    }
   ]
  },
  {
   "title": "Humidité Billes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  \"humidite_bille_1\" AS \"Témoin\",\n  \"humidite_bille_2\" AS \"Billes\"\nFROM \"environnement\" \nWHERE $timeFilter "
    }
   ]
  }
 ]
}