{
 "title": "Puits Canadien - Dashboard",
 "tags": [ "Général - Puit" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Temperature_Seuil",
    "query": "10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45"
   },
   {
    "name": "Vitesse_Seuil",
    "query": "30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100"
   }
  ]
 },
 "panels": [
  {
   "title": "Puits Canadien (Vue d'ensemble)",
   "type": "canvas",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "SELECT * FROM \"environnement\" WHERE $timeFilter ORDER BY \"time\" DESC LIMIT 1\n",
     "rawSql": "SELECT * FROM \"environnement\" ORDER BY \"time\" DESC LIMIT 1"
    }
   ]
  },
  { "title": "Données capteurs", "type": "dashlist", "gridPos": { "h": 8, "w": 7, "x": 15, "y": 0 } },
  {
   "title": "Batterie",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \n  \"batterie_pourcentage\"\nFROM \"environnement\" \nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Heures données reçue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT temperature_ambiant FROM \"environnement\" WHERE $timeFilter ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Contrôle Ventilateur",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "SELECT last(*) FROM \"Serre-puit\".\"consignes_ventilateur\" WHERE $timeFilter"
    }
   ]
  },
  { "title": "Alertes", "type": "alertlist", "gridPos": { "h": 10, "w": 9, "x": 15, "y": 11 } }
 ]
}